name: flutter_structure_generator
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  flutter_test:
    sdk: flutter
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
