name: flutter_structure_generator
description: A CLI tool for generating folder structures for Flutter projects
version: 1.0.2

environment:
  sdk: ^3.6.0

executables:
  flutter_structure_generator: flutter_structure_generator.dart

# Add regular dependencies here.
dependencies:
  args: ^2.6.0
  flutter_test:
    sdk: flutter
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
